package com.dchip.cloudparking.api.model.po;
// Generated 2018-11-30 17:46:32 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserThrid generated by hbm2java
 */
@Entity
@Table(name = "user_thrid", catalog = "cloud_parking")
public class UserThrid implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer flag;
	private String openId;

	public UserThrid() {
	}

	public UserThrid(String openId) {
		this.openId = openId;
	}

	public UserThrid(Integer userId, Integer flag, String openId) {
		this.userId = userId;
		this.flag = flag;
		this.openId = openId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "flag")
	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	@Column(name = "open_id", nullable = false, length = 100)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

}
