package com.dchip.cloudparking.api.model.po;
// Generated 2018-11-30 17:46:32 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParkingInfo generated by hbm2java
 */
@Entity
@Table(name = "parking_info", catalog = "cloud_parking")
public class ParkingInfo implements java.io.Serializable {

	private Integer id;
	private Integer parkCode;
	private String licensePlate;
	private Date parkDate;
	private Character status;
	private Integer userId;
	private Date outDate;
	private Integer isLock;
	private Integer appointmentId;
	private String imgUrl;
	private Integer carType;
	private Integer inRoadWayId;
	private Integer outRoadWayId;
	private Integer plateType;

	public ParkingInfo() {
	}

	public ParkingInfo(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public ParkingInfo(Integer parkCode, String licensePlate, Date parkDate, Character status, Integer userId,
			Date outDate, Integer isLock, Integer appointmentId, String imgUrl, Integer carType, Integer inRoadWayId,
			Integer outRoadWayId, Integer plateType) {
		this.parkCode = parkCode;
		this.licensePlate = licensePlate;
		this.parkDate = parkDate;
		this.status = status;
		this.userId = userId;
		this.outDate = outDate;
		this.isLock = isLock;
		this.appointmentId = appointmentId;
		this.imgUrl = imgUrl;
		this.carType = carType;
		this.inRoadWayId = inRoadWayId;
		this.outRoadWayId = outRoadWayId;
		this.plateType = plateType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "park_code")
	public Integer getParkCode() {
		return this.parkCode;
	}

	public void setParkCode(Integer parkCode) {
		this.parkCode = parkCode;
	}

	@Column(name = "license_plate", nullable = false, length = 20)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "park_date", length = 19)
	public Date getParkDate() {
		return this.parkDate;
	}

	public void setParkDate(Date parkDate) {
		this.parkDate = parkDate;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "out_date", length = 19)
	public Date getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	@Column(name = "is_lock")
	public Integer getIsLock() {
		return this.isLock;
	}

	public void setIsLock(Integer isLock) {
		this.isLock = isLock;
	}

	@Column(name = "appointment_id")
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "img_url", length = 65535)
	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	@Column(name = "car_type")
	public Integer getCarType() {
		return this.carType;
	}

	public void setCarType(Integer carType) {
		this.carType = carType;
	}

	@Column(name = "in_road_way_id")
	public Integer getInRoadWayId() {
		return this.inRoadWayId;
	}

	public void setInRoadWayId(Integer inRoadWayId) {
		this.inRoadWayId = inRoadWayId;
	}

	@Column(name = "out_road_way_id")
	public Integer getOutRoadWayId() {
		return this.outRoadWayId;
	}

	public void setOutRoadWayId(Integer outRoadWayId) {
		this.outRoadWayId = outRoadWayId;
	}

	@Column(name = "plate_type")
	public Integer getPlateType() {
		return this.plateType;
	}

	public void setPlateType(Integer plateType) {
		this.plateType = plateType;
	}

}
