package com.dchip.cloudparking.web.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CloneCar generated by hbm2java
 */
@Entity
@Table(name = "clone_car", catalog = "cloud_parking")
public class CloneCar implements java.io.Serializable {

	private Integer id;
	private Integer parkingInfoId;
	private Date createTime;
	private Integer status;

	public CloneCar() {
	}

	public CloneCar(Integer parkingInfoId, Date createTime, Integer status) {
		this.parkingInfoId = parkingInfoId;
		this.createTime = createTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parking_info_id")
	public Integer getParkingInfoId() {
		return this.parkingInfoId;
	}

	public void setParkingInfoId(Integer parkingInfoId) {
		this.parkingInfoId = parkingInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
