package com.dchip.cloudparking.web.model.po;
// Generated 2019-1-15 15:43:02 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginLog generated by hbm2java
 */
@Entity
@Table(name = "login_log", catalog = "cloud_parking")
public class LoginLog implements java.io.Serializable {


	private Integer id;
	private String ip;
	private Date loginAt;
	private int userId;
	private Integer sourceFlag;

	public LoginLog() {
	}

	public LoginLog(Date loginAt, int userId) {
		this.loginAt = loginAt;
		this.userId = userId;
	}

	public LoginLog(String ip, Date loginAt, int userId, Integer sourceFlag) {
		this.ip = ip;
		this.loginAt = loginAt;
		this.userId = userId;
		this.sourceFlag = sourceFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_at", nullable = false, length = 19)
	public Date getLoginAt() {
		return this.loginAt;
	}

	public void setLoginAt(Date loginAt) {
		this.loginAt = loginAt;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "source_flag")
	public Integer getSourceFlag() {
		return this.sourceFlag;
	}

	public void setSourceFlag(Integer sourceFlag) {
		this.sourceFlag = sourceFlag;
	}

}
