package com.dchip.cloudparking.web.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainRoadway generated by hbm2java
 */
@Entity
@Table(name = "main_roadway", catalog = "cloud_parking")
public class MainRoadway implements java.io.Serializable {

	private Integer id;
	private int mainId;
	private int roadwayId;
	private Date createTime;

	public MainRoadway() {
	}

	public MainRoadway(int mainId, int roadwayId) {
		this.mainId = mainId;
		this.roadwayId = roadwayId;
	}

	public MainRoadway(int mainId, int roadwayId, Date createTime) {
		this.mainId = mainId;
		this.roadwayId = roadwayId;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "main_id", nullable = false)
	public int getMainId() {
		return this.mainId;
	}

	public void setMainId(int mainId) {
		this.mainId = mainId;
	}

	@Column(name = "roadway_id", nullable = false)
	public int getRoadwayId() {
		return this.roadwayId;
	}

	public void setRoadwayId(int roadwayId) {
		this.roadwayId = roadwayId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
