package com.dchip.cloudparking.web.model.po;
// Generated 2019-1-2 15:46:32 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParkingUser generated by hbm2java
 */
@Entity
@Table(name = "parking_user", catalog = "cloud_parking")
public class ParkingUser implements java.io.Serializable {

	private Integer id;
	private String realName;
	private String userName;
	private String password;
	private int status;
	private Date createTime;
	private int type;
	private Integer parkingId;

	public ParkingUser() {
	}

	public ParkingUser(String realName, String userName, String password, int status, Date createTime, int type) {
		this.realName = realName;
		this.userName = userName;
		this.password = password;
		this.status = status;
		this.createTime = createTime;
		this.type = type;
	}

	public ParkingUser(String realName, String userName, String password, int status, Date createTime, int type,
			Integer parkingId) {
		this.realName = realName;
		this.userName = userName;
		this.password = password;
		this.status = status;
		this.createTime = createTime;
		this.type = type;
		this.parkingId = parkingId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "real_name", nullable = false, length = 50)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "user_name", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "parking_id")
	public Integer getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(Integer parkingId) {
		this.parkingId = parkingId;
	}

}
