package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-12-5 15:09:24 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParkingRule generated by hbm2java
 */
@Entity
@Table(name = "parking_rule", catalog = "cloud_parking")
public class ParkingRule implements java.io.Serializable {

	private int id;
	private int inRule;
	private Integer startDay;
	private Integer endDay;
	private String startTime;
	private String endTime;
	private Integer ruleType;

	public ParkingRule() {
	}

	public ParkingRule(int id, int inRule, int outRule) {
		this.id = id;
		this.inRule = inRule;
	}

	public ParkingRule(int id, int inRule, int outRule, Integer startDay, Integer endDay, String startTime,
			String endTime, Integer ruleType) {
		this.id = id;
		this.inRule = inRule;
		this.startDay = startDay;
		this.endDay = endDay;
		this.startTime = startTime;
		this.endTime = endTime;
		this.ruleType = ruleType;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "in_rule", nullable = false)
	public int getInRule() {
		return this.inRule;
	}

	public void setInRule(int inRule) {
		this.inRule = inRule;
	}

	@Column(name = "start_day")
	public Integer getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Integer startDay) {
		this.startDay = startDay;
	}

	@Column(name = "end_day")
	public Integer getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Integer endDay) {
		this.endDay = endDay;
	}

	@Column(name = "start_Time", length = 6)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_Time", length = 6)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "rule_type")
	public Integer getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(Integer ruleType) {
		this.ruleType = ruleType;
	}

}
