package com.dchip.cloudparking.api.model.po;
// Generated 2018-11-30 17:46:32 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserMessage generated by hbm2java
 */
@Entity
@Table(name = "user_message", catalog = "cloud_parking")
public class UserMessage implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String hasRead;

	public UserMessage() {
	}

	public UserMessage(Integer userId, String hasRead) {
		this.userId = userId;
		this.hasRead = hasRead;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "has_read")
	public String getHasRead() {
		return this.hasRead;
	}

	public void setHasRead(String hasRead) {
		this.hasRead = hasRead;
	}

}
