package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-11-13 16:21:40 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserCoupon generated by hbm2java
 */
@Entity
@Table(name = "user_coupon", catalog = "cloud_parking")
public class UserCoupon implements java.io.Serializable {

	private int id;
	private Integer userId;
	private Date createTime;
	private Date useTime;
	private Integer status;
	private Integer couponId;
	private Date endDate;

	public UserCoupon() {
	}

	public UserCoupon(int id, Date endDate) {
		this.id = id;
		this.endDate = endDate;
	}

	public UserCoupon(int id, Integer userId, Date createTime, Date useTime, Integer status, Integer couponId,
			Date endDate) {
		this.id = id;
		this.userId = userId;
		this.createTime = createTime;
		this.useTime = useTime;
		this.status = status;
		this.couponId = couponId;
		this.endDate = endDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "use_time", length = 19)
	public Date getUseTime() {
		return this.useTime;
	}

	public void setUseTime(Date useTime) {
		this.useTime = useTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "coupon_id")
	public Integer getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
