package com.dchip.cloudparking.api.model.po;
// Generated 2019-1-29 16:10:51 by Hibernate Tools 5.2.10.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card", catalog = "cloud_parking")
public class Card implements java.io.Serializable {

    private Integer id;
    private Integer parkingId;
    private String cardCode;
    private String carOwnerName;
    private Date expiryTime;
    private Integer max;
    private Integer type;
    private String remark;
    private String phone;
    private String address;
    private Integer isFixedSpace;

    public Card() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "parking_id")
    public Integer getParkingId() {
        return this.parkingId;
    }

    public void setParkingId(Integer parkingId) {
        this.parkingId = parkingId;
    }

    @Column(name = "card_code", length = 65535)
    public String getCardCode() {
        return this.cardCode;
    }

    public void setCardCode(String cardCode) {
        this.cardCode = cardCode;
    }

    @Column(name = "car_owner_name", length = 20)
    public String getCarOwnerName() {
        return this.carOwnerName;
    }

    public void setCarOwnerName(String carOwnerName) {
        this.carOwnerName = carOwnerName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "expiry_time", length = 19)
    public Date getExpiryTime() {
        return this.expiryTime;
    }

    public void setExpiryTime(Date expiryTime) {
        this.expiryTime = expiryTime;
    }

    @Column(name = "max")
    public Integer getMax() {
        return this.max;
    }

    public void setMax(Integer max) {
        this.max = max;
    }

    @Column(name = "type")
    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Column(name = "remark", length = 100)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "phone", length = 20)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "is_fixed_space", length = 2)
    public Integer getIsFixedSpace() {
        return isFixedSpace;
    }

    public void setIsFixedSpace(Integer isFixedSpace) {
        this.isFixedSpace = isFixedSpace;
    }
}
