package com.dchip.cloudparking.api.model.po;
// Generated 2018-11-30 17:46:32 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyBalanceWay generated by hbm2java
 */
@Entity
@Table(name = "company_balance_way", catalog = "cloud_parking")
public class CompanyBalanceWay implements java.io.Serializable {

	private Integer id;
	private String balanceAccount;
	private Integer balanceWay;
	private int companyId;
	private Date createTime;
	private Integer isFirst;
	private String bankCard;
	private String bankHolder;
	private String bankName;
	private String bankNum;

	public CompanyBalanceWay() {
	}

	public CompanyBalanceWay(int companyId) {
		this.companyId = companyId;
	}

	public CompanyBalanceWay(String balanceAccount, Integer balanceWay, int companyId, Date createTime, Integer isFirst,
			String bankCard, String bankHolder, String bankName, String bankNum) {
		this.balanceAccount = balanceAccount;
		this.balanceWay = balanceWay;
		this.companyId = companyId;
		this.createTime = createTime;
		this.isFirst = isFirst;
		this.bankCard = bankCard;
		this.bankHolder = bankHolder;
		this.bankName = bankName;
		this.bankNum = bankNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "balance_account", length = 50)
	public String getBalanceAccount() {
		return this.balanceAccount;
	}

	public void setBalanceAccount(String balanceAccount) {
		this.balanceAccount = balanceAccount;
	}

	@Column(name = "balance_way")
	public Integer getBalanceWay() {
		return this.balanceWay;
	}

	public void setBalanceWay(Integer balanceWay) {
		this.balanceWay = balanceWay;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "is_first")
	public Integer getIsFirst() {
		return this.isFirst;
	}

	public void setIsFirst(Integer isFirst) {
		this.isFirst = isFirst;
	}

	@Column(name = "bank_card", length = 50)
	public String getBankCard() {
		return this.bankCard;
	}

	public void setBankCard(String bankCard) {
		this.bankCard = bankCard;
	}

	@Column(name = "bank_holder", length = 50)
	public String getBankHolder() {
		return this.bankHolder;
	}

	public void setBankHolder(String bankHolder) {
		this.bankHolder = bankHolder;
	}

	@Column(name = "bank_name", length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_num", length = 50)
	public String getBankNum() {
		return this.bankNum;
	}

	public void setBankNum(String bankNum) {
		this.bankNum = bankNum;
	}

}
