package com.dchip.cloudparking.api.model.po;
// Generated 2018-12-14 15:59:22 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MainControlVersion generated by hbm2java
 */
@Entity
@Table(name = "main_control_version", catalog = "cloud_parking")
public class MainControlVersion implements java.io.Serializable {

	private Integer id;
	private String mac;
	private String currentVersion;
	private Date createTime;
	private String installFailReasion;
	private Integer type;

	public MainControlVersion() {
	}

	public MainControlVersion(String mac, String currentVersion, Date createTime, String installFailReasion,
			Integer type) {
		this.mac = mac;
		this.currentVersion = currentVersion;
		this.createTime = createTime;
		this.installFailReasion = installFailReasion;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mac", length = 50)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "current_version", length = 50)
	public String getCurrentVersion() {
		return this.currentVersion;
	}

	public void setCurrentVersion(String currentVersion) {
		this.currentVersion = currentVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "install_fail_reasion", length = 65535)
	public String getInstallFailReasion() {
		return this.installFailReasion;
	}

	public void setInstallFailReasion(String installFailReasion) {
		this.installFailReasion = installFailReasion;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
