package com.dchip.cloudparking.api.model.po;
// Generated 2019-4-2 14:59:51 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "cloud_parking")
public class Order implements java.io.Serializable {

	private Integer id;
	private BigDecimal fee;
	private Integer type;
	private Integer status;
	private Integer parkingInfoId;
	private int userId;
	private Date payTime;
	private BigDecimal discountAmount;
	private Integer couponId;
	private Integer parkingTime;
	private Integer isTransfer;
	private BigDecimal finalFee;
	private String outTradeNo;
	private Integer deductionId;
	private Integer appointmentId;
	private Integer staffId;
	private Integer applyCash;
	private Integer parkingConcessionId;

	public Order() {
	}

	public Order(int userId) {
		this.userId = userId;
	}

	public Order(BigDecimal fee, Integer type, Integer status, Integer parkingInfoId, int userId, Date payTime,
			BigDecimal discountAmount, Integer couponId, Integer parkingTime, Integer isTransfer, BigDecimal finalFee,
			String outTradeNo, Integer deductionId, Integer appointmentId, Integer staffId, Integer applyCash,
			Integer parkingConcessionId) {
		this.fee = fee;
		this.type = type;
		this.status = status;
		this.parkingInfoId = parkingInfoId;
		this.userId = userId;
		this.payTime = payTime;
		this.discountAmount = discountAmount;
		this.couponId = couponId;
		this.parkingTime = parkingTime;
		this.isTransfer = isTransfer;
		this.finalFee = finalFee;
		this.outTradeNo = outTradeNo;
		this.deductionId = deductionId;
		this.appointmentId = appointmentId;
		this.staffId = staffId;
		this.applyCash = applyCash;
		this.parkingConcessionId = parkingConcessionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fee", precision = 8)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parking_info_id")
	public Integer getParkingInfoId() {
		return this.parkingInfoId;
	}

	public void setParkingInfoId(Integer parkingInfoId) {
		this.parkingInfoId = parkingInfoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_time", length = 19)
	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "discount_amount", precision = 8)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "coupon_id")
	public Integer getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	@Column(name = "parking_time")
	public Integer getParkingTime() {
		return this.parkingTime;
	}

	public void setParkingTime(Integer parkingTime) {
		this.parkingTime = parkingTime;
	}

	@Column(name = "is_transfer")
	public Integer getIsTransfer() {
		return this.isTransfer;
	}

	public void setIsTransfer(Integer isTransfer) {
		this.isTransfer = isTransfer;
	}

	@Column(name = "final_fee", precision = 8)
	public BigDecimal getFinalFee() {
		return this.finalFee;
	}

	public void setFinalFee(BigDecimal finalFee) {
		this.finalFee = finalFee;
	}

	@Column(name = "out_trade_no")
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "deduction_id")
	public Integer getDeductionId() {
		return this.deductionId;
	}

	public void setDeductionId(Integer deductionId) {
		this.deductionId = deductionId;
	}

	@Column(name = "appointment_id")
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "staff_id")
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "apply_cash")
	public Integer getApplyCash() {
		return this.applyCash;
	}

	public void setApplyCash(Integer applyCash) {
		this.applyCash = applyCash;
	}

	@Column(name = "parking_concession_id")
	public Integer getParkingConcessionId() {
		return this.parkingConcessionId;
	}

	public void setParkingConcessionId(Integer parkingConcessionId) {
		this.parkingConcessionId = parkingConcessionId;
	}

}
