package com.dchip.cloudparking.api.model.po;
// Generated 2018-12-5 15:09:24 by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParkingRule generated by hbm2java
 */
@Entity
@Table(name = "parking_rule", catalog = "cloud_parking")
public class ParkingRule implements java.io.Serializable {

	private Integer id;
	private Integer inRule;
	private Integer startDay;
	private Integer endDay;
	private String startTime;
	private String endTime;
	private Integer ruleType;

	public ParkingRule() {
	}

	public ParkingRule(Integer inRule, Integer startDay, Integer endDay, String startTime,
			String endTime, Integer ruleType) {
		this.inRule = inRule;
		this.startDay = startDay;
		this.endDay = endDay;
		this.startTime = startTime;
		this.endTime = endTime;
		this.ruleType = ruleType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "in_rule", nullable = false)
	public Integer getInRule() {
		return this.inRule;
	}

	public void setInRule(Integer inRule) {
		this.inRule = inRule;
	}

	@Column(name = "start_day")
	public Integer getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Integer startDay) {
		this.startDay = startDay;
	}

	@Column(name = "end_day")
	public Integer getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Integer endDay) {
		this.endDay = endDay;
	}

	@Column(name = "start_Time", length = 6)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_Time", length = 6)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "rule_type")
	public Integer getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(Integer ruleType) {
		this.ruleType = ruleType;
	}

}
