package com.dchip.cloudparking.api.model.po;
// Generated 2018-12-29 18:07:22 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SecondPlateName generated by hbm2java
 */
@Entity
@Table(name = "second_plate_name", catalog = "cloud_parking")
public class SecondPlateName implements java.io.Serializable {

	private Integer id;
	private Date createTime;
	private String licensePlate;
	private Integer status;
	private Integer parkingId;
	private Integer tmpFlag;

	public SecondPlateName() {
	}

	public SecondPlateName(Date createTime, String licensePlate, Integer status, Integer parkingId, Integer tmpFlag) {
		this.createTime = createTime;
		this.licensePlate = licensePlate;
		this.status = status;
		this.parkingId = parkingId;
		this.tmpFlag = tmpFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "license_plate", length = 10)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parking_id")
	public Integer getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(Integer parkingId) {
		this.parkingId = parkingId;
	}

	@Column(name = "tmp_flag")
	public Integer getTmpFlag() {
		return this.tmpFlag;
	}

	public void setTmpFlag(Integer tmpFlag) {
		this.tmpFlag = tmpFlag;
	}

}
