package com.dchip.cloudparking.web.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RechargeLog generated by hbm2java
 */
@Entity
@Table(name = "recharge_log", catalog = "cloud_parking")
public class RechargeLog implements java.io.Serializable {

	private Integer id;
	private BigDecimal inMoney;
	private BigDecimal discountMoney;
	private Date rechargeDate;
	private boolean status;
	private int userId;
	private String outTradeNo;
	private Integer type;

	public RechargeLog() {
	}

	public RechargeLog(BigDecimal inMoney, BigDecimal discountMoney, Date rechargeDate, boolean status, int userId) {
		this.inMoney = inMoney;
		this.discountMoney = discountMoney;
		this.rechargeDate = rechargeDate;
		this.status = status;
		this.userId = userId;
	}

	public RechargeLog(BigDecimal inMoney, BigDecimal discountMoney, Date rechargeDate, boolean status, int userId,
			String outTradeNo, Integer type) {
		this.inMoney = inMoney;
		this.discountMoney = discountMoney;
		this.rechargeDate = rechargeDate;
		this.status = status;
		this.userId = userId;
		this.outTradeNo = outTradeNo;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "in_money", nullable = false, precision = 20)
	public BigDecimal getInMoney() {
		return this.inMoney;
	}

	public void setInMoney(BigDecimal inMoney) {
		this.inMoney = inMoney;
	}

	@Column(name = "discount_money", nullable = false, precision = 20)
	public BigDecimal getDiscountMoney() {
		return this.discountMoney;
	}

	public void setDiscountMoney(BigDecimal discountMoney) {
		this.discountMoney = discountMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recharge_date", nullable = false, length = 19)
	public Date getRechargeDate() {
		return this.rechargeDate;
	}

	public void setRechargeDate(Date rechargeDate) {
		this.rechargeDate = rechargeDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "out_trade_no")
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
