package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-12-4 18:10:34 by Hibernate Tools 5.2.10.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CardLicensePlate generated by hbm2java
 */
@Entity
@Table(name = "card_license_plate", catalog = "cloud_parking")
public class CardLicensePlate implements java.io.Serializable {

	private int id;
	private int cardId;
	private String lisencePlate;
	private int isMain;

	public CardLicensePlate() {
	}


	public CardLicensePlate(int id, int cardId, String lisencePlate, int isMain) {
		this.id = id;
		this.cardId = cardId;
		this.lisencePlate = lisencePlate;
		this.isMain = isMain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "card_id", nullable = false)
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	@Column(name = "lisence_plate", nullable = false, length = 10,columnDefinition = "varchar(10) default ''")
	public String getLisencePlate() {
		return this.lisencePlate;
	}

	public void setLisencePlate(String lisencePlate) {
		this.lisencePlate = lisencePlate;
	}

	@Column(name = "is_main", length = 1,nullable = false)
	public int getIsMain() {
		return this.isMain;
	}

	public void setIsMain(int isMain) {
		this.isMain = isMain;
	}

}
