package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-10-16 17:04:35 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LockControl generated by hbm2java
 */
@Entity
@Table(name = "lock_control", catalog = "cloud_parking")
public class LockControl implements java.io.Serializable {

	private int id;
	private String version;
	private int mainId;
	private String uid;
	private Date createTime;
	private Integer online;

	public LockControl() {
	}

	public LockControl(int id, int mainId) {
		this.id = id;
		this.mainId = mainId;
	}

	public LockControl(int id, int mainId, String uid, Date createTime, Integer online) {
		this.id = id;
		this.mainId = mainId;
		this.uid = uid;
		this.createTime = createTime;
		this.online = online;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@Column(name = "version", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "main_id", nullable = false)
	public int getMainId() {
		return this.mainId;
	}

	public void setMainId(int mainId) {
		this.mainId = mainId;
	}

	@Column(name = "uid", length = 50)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "online")
	public Integer getOnline() {
		return this.online;
	}

	public void setOnline(Integer online) {
		this.online = online;
	}

}
