package com.dchip.cloudparking.api.model.po;
// Generated 2018-12-12 17:45:57 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parking generated by hbm2java
 */
@Entity
@Table(name = "parking", catalog = "cloud_parking")
public class Parking implements java.io.Serializable {

	private Integer id;
	private int parkCode;
	private String parkName;
	private String provinceName;
	private String cityName;
	private String areaName;
	private String location;
	private String longitude;
	private String latitude;
	private String status;
	private Integer freeStandardId;
	private Integer companyId;
	private String comcatName;
	private String comcatPhone;
	private String managerName;
	private String managerPhone;
	private Integer calculateDay;
	private Date createTime;
	private Integer spaceCount;
	private BigDecimal monthFree;
	private Integer max;
	private Integer isSupportCard;
	private Integer freeTimePayFlag;

	public Parking() {
	}

	public Parking(int parkCode, String parkName) {
		this.parkCode = parkCode;
		this.parkName = parkName;
	}

	public Parking(int parkCode, String parkName, String provinceName, String cityName, String areaName,
			String location, String longitude, String latitude, String status, Integer freeStandardId,
			Integer companyId, String comcatName, String comcatPhone, String managerName, String managerPhone,
			Integer calculateDay, Date createTime, Integer spaceCount, BigDecimal monthFree, Integer max,
			Integer isSupportCard, Integer freeTimePayFlag) {
		this.parkCode = parkCode;
		this.parkName = parkName;
		this.provinceName = provinceName;
		this.cityName = cityName;
		this.areaName = areaName;
		this.location = location;
		this.longitude = longitude;
		this.latitude = latitude;
		this.status = status;
		this.freeStandardId = freeStandardId;
		this.companyId = companyId;
		this.comcatName = comcatName;
		this.comcatPhone = comcatPhone;
		this.managerName = managerName;
		this.managerPhone = managerPhone;
		this.calculateDay = calculateDay;
		this.createTime = createTime;
		this.spaceCount = spaceCount;
		this.monthFree = monthFree;
		this.max = max;
		this.isSupportCard = isSupportCard;
		this.freeTimePayFlag=freeTimePayFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "park_code", nullable = false)
	public int getParkCode() {
		return this.parkCode;
	}

	public void setParkCode(int parkCode) {
		this.parkCode = parkCode;
	}

	@Column(name = "park_name", nullable = false, length = 100)
	public String getParkName() {
		return this.parkName;
	}

	public void setParkName(String parkName) {
		this.parkName = parkName;
	}

	@Column(name = "province_name", length = 20)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "city_name", length = 20)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "area_name", length = 20)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "longitude", length = 50)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", length = 50)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "free_standard_id")
	public Integer getFreeStandardId() {
		return this.freeStandardId;
	}

	public void setFreeStandardId(Integer freeStandardId) {
		this.freeStandardId = freeStandardId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "comcat_name", length = 20)
	public String getComcatName() {
		return this.comcatName;
	}

	public void setComcatName(String comcatName) {
		this.comcatName = comcatName;
	}

	@Column(name = "comcat_phone", length = 20)
	public String getComcatPhone() {
		return this.comcatPhone;
	}

	public void setComcatPhone(String comcatPhone) {
		this.comcatPhone = comcatPhone;
	}

	@Column(name = "manager_name", length = 20)
	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	@Column(name = "manager_phone", length = 20)
	public String getManagerPhone() {
		return this.managerPhone;
	}

	public void setManagerPhone(String managerPhone) {
		this.managerPhone = managerPhone;
	}

	@Column(name = "calculate_day")
	public Integer getCalculateDay() {
		return this.calculateDay;
	}

	public void setCalculateDay(Integer calculateDay) {
		this.calculateDay = calculateDay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "space_count")
	public Integer getSpaceCount() {
		return this.spaceCount;
	}

	public void setSpaceCount(Integer spaceCount) {
		this.spaceCount = spaceCount;
	}

	@Column(name = "month_free", precision = 11)
	public BigDecimal getMonthFree() {
		return this.monthFree;
	}

	public void setMonthFree(BigDecimal monthFree) {
		this.monthFree = monthFree;
	}

	@Column(name = "max")
	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

	@Column(name = "is_support_card")
	public Integer getIsSupportCard() {
		return this.isSupportCard;
	}

	public void setIsSupportCard(Integer isSupportCard) {
		this.isSupportCard = isSupportCard;
	}
	
	@Column(name = "free_time_pay_flag")
	public Integer getFreeTimePayFlag() {
		return freeTimePayFlag;
	}

	public void setFreeTimePayFlag(Integer freeTimePayFlag) {
		this.freeTimePayFlag = freeTimePayFlag;
	}
	
	

}
