package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-11-28 10:36:33 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthlyCard generated by hbm2java
 */
@Entity
@Table(name = "monthly_card", catalog = "cloud_parking")
public class MonthlyCard implements java.io.Serializable {

	private Integer id;
	private Integer parkingId;
	private String licensePlate;
	private String carOwnerName;
	private Date expiryTime;
	private Integer type;
	private Date startTime;
	private Date endTime;

	public MonthlyCard() {
	}

	public MonthlyCard(Integer parkingId, String licensePlate, String carOwnerName, Date expiryTime, Integer type,
			Date startTime, Date endTime) {
		this.parkingId = parkingId;
		this.licensePlate = licensePlate;
		this.carOwnerName = carOwnerName;
		this.expiryTime = expiryTime;
		this.type = type;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parking_id")
	public Integer getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(Integer parkingId) {
		this.parkingId = parkingId;
	}

	@Column(name = "license_plate", length = 50)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "car_owner_name", length = 20)
	public String getCarOwnerName() {
		return this.carOwnerName;
	}

	public void setCarOwnerName(String carOwnerName) {
		this.carOwnerName = carOwnerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_time", length = 19)
	public Date getExpiryTime() {
		return this.expiryTime;
	}

	public void setExpiryTime(Date expiryTime) {
		this.expiryTime = expiryTime;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
