package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-12-4 19:04:28 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "cloud_parking")
public class Order implements java.io.Serializable {

	private Integer id;
	private BigDecimal fee;
	private Integer type;
	private Integer status;
	private Integer parkingInfoId;
	private Integer userId;
	private Date payTime;
	private Integer couponId;
	private BigDecimal discountAmount;
	private Integer parkingTime;
	private Integer isTransfer;
	private BigDecimal finalFee;
	private String outTradeNo;
	private Integer deductionId;
	private Integer appointmentId;
	private Integer applyCash;

	public Order() {
	}

	public Order(Integer parkingInfoId, Integer userId) {
		this.parkingInfoId = parkingInfoId;
		this.userId = userId;
	}

	public Order(BigDecimal fee, Integer type, Integer status, Integer parkingInfoId, Integer userId, Date payTime,
			Integer couponId, BigDecimal discountAmount, Integer parkingTime, Integer isTransfer, BigDecimal finalFee,
			String outTradeNo, Integer deductionId, Integer appointmentId, Integer applyCash) {
		this.fee = fee;
		this.type = type;
		this.status = status;
		this.parkingInfoId = parkingInfoId;
		this.userId = userId;
		this.payTime = payTime;
		this.couponId = couponId;
		this.discountAmount = discountAmount;
		this.parkingTime = parkingTime;
		this.isTransfer = isTransfer;
		this.finalFee = finalFee;
		this.outTradeNo = outTradeNo;
		this.deductionId = deductionId;
		this.appointmentId = appointmentId;
		this.applyCash = applyCash;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fee", precision = 8)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parking_info_id", nullable = false)
	public Integer getParkingInfoId() {
		return this.parkingInfoId;
	}

	public void setParkingInfoId(Integer parkingInfoId) {
		this.parkingInfoId = parkingInfoId;
	}

	@Column(name = "user_id", nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_time", length = 19)
	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "coupon_id")
	public Integer getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	@Column(name = "discount_amount", precision = 8)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "parking_time")
	public Integer getParkingTime() {
		return this.parkingTime;
	}

	public void setParkingTime(Integer parkingTime) {
		this.parkingTime = parkingTime;
	}

	@Column(name = "is_transfer")
	public Integer getIsTransfer() {
		return this.isTransfer;
	}

	public void setIsTransfer(Integer isTransfer) {
		this.isTransfer = isTransfer;
	}

	@Column(name = "final_fee")
	public BigDecimal getFinalFee() {
		return this.finalFee;
	}

	public void setFinalFee(BigDecimal finalFee) {
		this.finalFee = finalFee;
	}

	@Column(name = "out_trade_no")
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "deduction_id")
	public Integer getDeductionId() {
		return this.deductionId;
	}

	public void setDeductionId(Integer deductionId) {
		this.deductionId = deductionId;
	}

	@Column(name = "appointment_id")
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "apply_cash")
	public Integer getApplyCash() {
		return this.applyCash;
	}

	public void setApplyCash(Integer applyCash) {
		this.applyCash = applyCash;
	}

}
