package com.dchip.cloudparking.api.model.po;
// Generated 2018-11-30 17:46:32 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WechatConfig generated by hbm2java
 */
@Entity
@Table(name = "wechat_config", catalog = "cloud_parking")
public class WechatConfig implements java.io.Serializable {

	private Integer id;
	private String accessToken;
	private String jsapiTicket;
	private String timeStamp;

	public WechatConfig() {
	}

	public WechatConfig(String accessToken, String jsapiTicket, String timeStamp) {
		this.accessToken = accessToken;
		this.jsapiTicket = jsapiTicket;
		this.timeStamp = timeStamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "access_token", length = 200)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "jsapi_ticket", length = 200)
	public String getJsapiTicket() {
		return this.jsapiTicket;
	}

	public void setJsapiTicket(String jsapiTicket) {
		this.jsapiTicket = jsapiTicket;
	}

	@Column(name = "time_stamp", length = 200)
	public String getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}

}
