package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-12-4 18:10:34 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card", catalog = "cloud_parking")
public class Card implements java.io.Serializable {

	private int id;
	private Integer parkingId;
	private String cardCode;
	private String carOwnerName;
	private Date expiryTime;
	private Integer max;
	private Integer type;

	public Card() {
	}

	public Card(int id) {
		this.id = id;
	}

	public Card(int id, Integer parkingId, String cardCode, String carOwnerName, Date expiryTime,Integer max,Integer type) {
		this.id = id;
		this.parkingId = parkingId;
		this.cardCode = cardCode;
		this.carOwnerName = carOwnerName;
		this.expiryTime = expiryTime;
		this.max = max;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "parking_id")
	public Integer getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(Integer parkingId) {
		this.parkingId = parkingId;
	}

	@Column(name = "card_code", length = 65535)
	public String getCardCode() {
		return this.cardCode;
	}

	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}

	@Column(name = "car_owner_name", length = 20)
	public String getCarOwnerName() {
		return this.carOwnerName;
	}

	public void setCarOwnerName(String carOwnerName) {
		this.carOwnerName = carOwnerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_time", length = 19)
	public Date getExpiryTime() {
		return this.expiryTime;
	}

	public void setExpiryTime(Date expiryTime) {
		this.expiryTime = expiryTime;
	}

	@Column(name = "max",length = 2,nullable = false)
	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

	@Column(name = "type",length = 2,nullable = false,columnDefinition = "int(2) default '1'")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
