package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FreeStandard generated by hbm2java
 */
@Entity
@Table(name = "free_standard", catalog = "cloud_parking")
public class FreeStandard implements java.io.Serializable {

	private Integer id;
	private Integer freeTimeLength;
	private BigDecimal hourCost;
	private BigDecimal mostCost;
	private Integer freeModelId;

	public FreeStandard() {
	}

	public FreeStandard(Integer freeTimeLength, BigDecimal hourCost, BigDecimal mostCost, Integer freeModelId) {
		this.freeTimeLength = freeTimeLength;
		this.hourCost = hourCost;
		this.mostCost = mostCost;
		this.freeModelId = freeModelId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "free_time_length")
	public Integer getFreeTimeLength() {
		return this.freeTimeLength;
	}

	public void setFreeTimeLength(Integer freeTimeLength) {
		this.freeTimeLength = freeTimeLength;
	}

	@Column(name = "hour_cost", precision = 10)
	public BigDecimal getHourCost() {
		return this.hourCost;
	}

	public void setHourCost(BigDecimal hourCost) {
		this.hourCost = hourCost;
	}

	@Column(name = "most_cost", precision = 10)
	public BigDecimal getMostCost() {
		return this.mostCost;
	}

	public void setMostCost(BigDecimal mostCost) {
		this.mostCost = mostCost;
	}

	@Column(name = "free_model_id")
	public Integer getFreeModelId() {
		return this.freeModelId;
	}

	public void setFreeModelId(Integer freeModelId) {
		this.freeModelId = freeModelId;
	}

}
