package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointment generated by hbm2java
 */
@Entity
@Table(name = "appointment", catalog = "cloud_parking")
public class Appointment implements java.io.Serializable {

	private Integer id;
	private int parkingId;
	private int userId;
	private Date createTime;
	private Date appointStartTime;
	private Integer status;
	private String licensePlate;

	public Appointment() {
	}

	public Appointment(int parkingId, int userId, Date createTime, Date appointStartTime) {
		this.parkingId = parkingId;
		this.userId = userId;
		this.createTime = createTime;
		this.appointStartTime = appointStartTime;
	}

	public Appointment(int parkingId, int userId, Date createTime, Date appointStartTime, Integer status,
			String licensePlate) {
		this.parkingId = parkingId;
		this.userId = userId;
		this.createTime = createTime;
		this.appointStartTime = appointStartTime;
		this.status = status;
		this.licensePlate = licensePlate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parking_id", nullable = false)
	public int getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(int parkingId) {
		this.parkingId = parkingId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appoint_start_time", nullable = false, length = 19)
	public Date getAppointStartTime() {
		return this.appointStartTime;
	}

	public void setAppointStartTime(Date appointStartTime) {
		this.appointStartTime = appointStartTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "license_plate", length = 50)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

}
