package com.dchip.cloudparking.wechat.model.po;
// Generated 2019-1-2 20:52:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeductionModel generated by hbm2java
 */
@Entity
@Table(name = "deduction_model", catalog = "cloud_parking")
public class DeductionModel implements java.io.Serializable {

	private Integer id;
	private String name;
	private int parkingId;
	private int hourNum;
	private Date dueTime;
	private Integer status;

	public DeductionModel() {
	}

	public DeductionModel(String name, int parkingId, int hourNum) {
		this.name = name;
		this.parkingId = parkingId;
		this.hourNum = hourNum;
	}

	public DeductionModel(String name, int parkingId, int hourNum, Date dueTime, Integer status) {
		this.name = name;
		this.parkingId = parkingId;
		this.hourNum = hourNum;
		this.dueTime = dueTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parking_id", nullable = false)
	public int getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(int parkingId) {
		this.parkingId = parkingId;
	}

	@Column(name = "hour_num", nullable = false)
	public int getHourNum() {
		return this.hourNum;
	}

	public void setHourNum(int hourNum) {
		this.hourNum = hourNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_time", length = 19)
	public Date getDueTime() {
		return this.dueTime;
	}

	public void setDueTime(Date dueTime) {
		this.dueTime = dueTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
