package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-11-1 11:18:16 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserMessage generated by hbm2java
 */
@Entity
@Table(name = "user_message", catalog = "cloud_parking")
public class UserMessage implements java.io.Serializable {

	private int id;
	private Integer userId;
	private String hasRead;

	public UserMessage() {
	}

	public UserMessage(int id) {
		this.id = id;
	}

	public UserMessage(int id, Integer userId, String hasRead) {
		this.id = id;
		this.userId = userId;
		this.hasRead = hasRead;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "has_read")
	public String getHasRead() {
		return this.hasRead;
	}

	public void setHasRead(String hasRead) {
		this.hasRead = hasRead;
	}

}
