package com.dchip.cloudparking.wechat.model.po;
// Generated 2018-12-12 19:59:29 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FirstWhiteList generated by hbm2java
 */
@Entity
@Table(name = "first_white_list", catalog = "cloud_parking")
public class FirstWhiteList implements java.io.Serializable {

	private Integer id;
	private Date createTime;
	private String licensePlateName;
	private Integer licensePlateTypeId;

	public FirstWhiteList() {
	}

	public FirstWhiteList(Date createTime, String licensePlateName, Integer type, Integer licensePlateTypeId) {
		this.createTime = createTime;
		this.licensePlateName = licensePlateName;
		this.licensePlateTypeId = licensePlateTypeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "license_plate_name", length = 10)
	public String getLicensePlateName() {
		return this.licensePlateName;
	}

	public void setLicensePlateName(String licensePlateName) {
		this.licensePlateName = licensePlateName;
	}

	@Column(name = "license_plate_type_id")
	public Integer getLicensePlateTypeId() {
		return this.licensePlateTypeId;
	}

	public void setLicensePlateTypeId(Integer licensePlateTypeId) {
		this.licensePlateTypeId = licensePlateTypeId;
	}

}
